version: '3.8'

services:
  db:
    image: postgres
    volumes:
        - ./postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./.env
  web:
    image: frolkit/api_yamdb
    restart: always
    depends_on:
        - db
    volumes:
        - ./static:/code/static/
    env_file:
        - ./.env
  nginx:
    image: frolkit/nginx
    restart: always
    depends_on:
        - web
    volumes:
        - ./static:/etc/nginx/static/
    ports:
        - "8020:80"

